[package]
name = "yaml2env"
version = "0.1.0"
authors = ["vikin91 <vikin91@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.4"
clap = "2.33.3"
simple-error = "0.2.2"
