name: Cross-compile binaries for the release

on:
  workflow_dispatch:
    inputs:
      versionTag:
        description: "Version tag (e.g., v1.2.3)"
        default: v0.0.1
        required: true

jobs:
  release:
    name: Cross Build
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            use-cross: true
          - os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
          # - os: macos-latest
          #   target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.versionTag }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Calculate checksums
        run: |
          sha256sum target/${{ matrix.target }}/release/yaml2env | sed 's, .*/, ,' > target/${{ matrix.target }}/release/yaml2env.sha256sum
      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/yaml2env
          asset_name: yaml2env-${{ matrix.target }}
          tag: ${{ github.event.inputs.versionTag }}
      - name: Upload sha256sum
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/yaml2env.sha256sum
          asset_name: yaml2env-${{ matrix.target }}.sha256sum
          tag: ${{ github.event.inputs.versionTag }}
          overwrite: true
